#!/bin/bash

rm ~/x

echo "Đang cài đặt các gói cần thiết...
"
pkg install termux-am -y &>/dev/null

termux-setup-storage & sleep 4 &>/dev/null

while true; do
    if [ -d ~/storage/shared ]; then
        break
    else
        echo "Quyên truy cập bộ nhớ bị từ chối."
    fi
    sleep 3
done

echo "Đang setup, đợi tí
"
apt-get clean
apt-get update >/dev/null 2>&1
apt-get -y --with-new-pkgs -o Dpkg::Options::="--force-confdef" upgrade >/dev/null 2>&1
pkg install x11-repo -y &>/dev/null
pkg install pulseaudio -y &>/dev/null
pkg install xwayland -y &>/dev/null
pkg install wget -y &>/dev/null
pkg install tsu -y &>/dev/null
pkg install root-repo -y &>/dev/null
pkg install patchelf -y &>/dev/null
pkg install p7zip -y &>/dev/null
pkg install xorg-xrandr -y &>/dev/null
pkg install ncurses-utils -y &>/dev/null
pkg install hashdeep -y &>/dev/null
pkg install termux-x11-nightly -y &>/dev/null

if [ -e $PREFIX/glibc ]; then
    echo -n "Gỡ môi trường glibc cũ, tiếp tục chứ ? (C/n) "
    read i
    if [ "$i" = "C" ] || [ "$i" = "c" ]; then
        rm -rf $PREFIX/glibc
    else
        return 1
    fi
fi

INSTALL_WOW64=0

echo "Vui lòng chọn 1 trong 2 phiên bản mobox
"
echo "1) Cài mobox chạy với box86/64
"
echo "2) Cài mobox chạy mỗi box64 kèm wow64 (Khuyến nghị)
"
echo ""
echo -n "Chọn 1 trong 2 cái : "
read i
case "$i" in
1)
    INSTALL_WOW64=0
;;
2)
    INSTALL_WOW64=1
;;
*)
    return 1
;;
esac

echo "Đang cài mobox
"

function wget-git-q {
    wget -q --retry-connrefused --tries=0 --header "PRIVATE-TOKEN: $PRIVATE_TOKEN" "https://gitlab.com/api/v4/projects/$PROJECT_ID/repository/files/$1/raw?ref=main" -O $2
    return $?
}

echo "Cập nhật trình quản lý gói"
mkdir -p $PREFIX/glibc/opt/package-manager/installed

if [ "$INSTALL_WOW64" = "1" ]; then
echo "PRIVATE_TOKEN=glpat-h5r7HjKoPKZPxmfg79xs
PROJECT_ID=54240888">$PREFIX/glibc/opt/package-manager/token
else
echo "PRIVATE_TOKEN=glpat-Xs4HfrCkMpbedkPycqzP
PROJECT_ID=52465323">$PREFIX/glibc/opt/package-manager/token
fi

. $PREFIX/glibc/opt/package-manager/token
if ! wget-git-q "package-manager" "$PREFIX/glibc/opt/package-manager/package-manager"; then
    echo "Download failed"
    return 1
fi
. $PREFIX/glibc/opt/package-manager/package-manager
sync-all

if [ "$INSTALL_WOW64" = "1" ]; then
sync-package wine-9.3-vanilla-wow64
else
sync-package wine-ge-custom-8-25
fi

ln -sf $PREFIX/glibc/opt/scripts/mobox $PREFIX/bin/mobox

ln -sf $PREFIX/glibc/opt/scripts/mobox $PREFIX/bin/nekobox

echo "Tiến hành cập nhật bản Việt hoá"



FILE_ID="18Cjf-kKe8HpyPulu06qsB2vOUFAkm5uj"

TEMP_FILE="/data/data/com.termux/files/usr/tmp/file.tar.gz"

DEST_DIR="/data/data/com.termux/files/usr/glibc/opt/"

CONFIRM=$(wget --quiet --save-cookies /tmp/cookies.txt --keep-session-cookies --no-check-certificate \
    "https://drive.google.com/uc?export=download&id=$FILE_ID" -O- | \
    sed -rn 's/.confirm=([0-9A-Za-z_]+).*/\1/p')
wget --load-cookies /tmp/cookies.txt "https://drive.google.com/uc?export=download&confirm=$CONFIRM&id=$FILE_ID" \
    -O $TEMP_FILE
rm -rf /tmp/cookies.txt

rm -rf /data/data/com.termux/files/usr/glibc/opt/scripts

tar -xzvf $TEMP_FILE -C $DEST_DIR
rm $TEMP_FILE

echo "Cập nhật thành công."

echo "Cài đặt thành công. Để khởi động - nhập \"mobox\".

