#!/bin/bash
FILE="$HOME/.check"
if [ ! -f "$FILE" ]; then

echo "Đang setup, đợi tí
"
pacman -Sy
pacman -S termux-am pulseaudio xwayland wget tsu patchelf p7zip xorg-xrandr hashdeep ncurses-utils termux-x11-nightly
    touch "$FILE"
bash x
else

while true; do
    if [ -d ~/storage/shared ]; then
        break
    else
        echo "Quyên truy cập bộ nhớ bị từ chối."
    fi
    sleep 3
done
clear
rm ~/x
echo "Bạn có muốn cài 2 phiên bản mobox không ? (Quá trình này cần ít nhất 3GB để cài) (C/k)"
read u
if [ "$u" = "C" ] || [ "$u" = "c" ]; then
wget https://raw.githubusercontent.com/NekoKatoriChan/mobox/main/files/install-2 -O x2
elif [ "$u" = "K" ] || [ "$u" = "k" ]; then
clear
fi

if [ -e $PREFIX/glibc ]; then
    echo -n "Gỡ môi trường glibc cũ, tiếp tục chứ ? (C/k) "
    read i
    if [ "$i" = "C" ] || [ "$i" = "c" ]; then
        rm -rf $PREFIX/glibc
    elif [ "$i" = "K" ] || [ "$i" = "k" ]; then
        exit 1
else
	exit 1
    fi
fi

INSTALL_WOW64=0

echo "Vui lòng chọn 1 trong 2 phiên bản mobox
"
echo "1) Cài mobox chạy với box86/64
"
echo "2) Cài mobox chạy mỗi box64 kèm wow64 (Khuyến nghị)
"
echo ""
echo -n "Chọn 1 trong 2 cái : "
read i
case "$i" in
1)
    INSTALL_WOW64=0
;;
2)
    INSTALL_WOW64=1
;;
*)
    return 1
;;
esac

echo "Đang cài mobox
"

function wget-git-q {
    wget -q --retry-connrefused --tries=0 "https://gitlab.com/api/v4/projects/$PROJECT_ID/repository/files/$1/raw?ref=main" -O $2
    return $?
}

echo "Cập nhật trình quản lý gói"
mkdir -p $PREFIX/glibc/opt/package-manager/installed
if [ "$INSTALL_WOW64" = "1" ]; then
echo "PROJECT_ID=54240888">$PREFIX/glibc/opt/package-manager/token
else
echo "PROJECT_ID=52465323">$PREFIX/glibc/opt/package-manager/token
fi

. $PREFIX/glibc/opt/package-manager/token
if ! wget-git-q "package-manager" "$PREFIX/glibc/opt/package-manager/package-manager"; then
    echo "Tải xuống thất bại"
    return 1
fi
. $PREFIX/glibc/opt/package-manager/package-manager
sync-all

if [ "$INSTALL_WOW64" = "1" ]; then
sync-package wine-9.3-vanilla-wow64
rm -rf /data/data/com.termux/files/usr/glibc/opt/scripts
wget https://github.com/NekoKatoriChan/mobox-vietnamese/raw/refs/heads/main/stable/uwu.gz
tar -xvf uwu.gz
mv scripts $PREFIX/glibc/opt/
rm uwu.gz
wget https://files.catbox.moe/3n6ghr.xz -O wine.xz
tar xvf wine.xz
rm -rf $PREFIX/glibc/wine-9.3-vanilla-wow64/bin
rm -rf $PREFIX/glibc/wine-9.3-vanilla-wow64/lib
rm -rf $PREFIX/glibc/wine-9.3-vanilla-wow64/share
cd wine
mv bin $PREFIX/glibc/wine-9.3-vanilla-wow64/
mv lib $PREFIX/glibc/wine-9.3-vanilla-wow64/
mv share $PREFIX/glibc/wine-9.3-vanilla-wow64/
else
sync-package wine-ge-custom-8-25
rm -rf $PREFIX/glibc/opt/scripts
wget https://github.com/NekoKatoriChan/mobox-vietnamese/raw/refs/heads/main/unstable-mobox/uwu-box86.gz
tar -xvf uwu-box86.gz
mv scripts $PREFIX/glibc/opt/
rm uwu-box86.gz
fi
clear

ln -sf $PREFIX/glibc/opt/scripts/mobox $PREFIX/bin/mobox

ln -sf $PREFIX/glibc/opt/scripts/mobox $PREFIX/bin/nekobox

sleep 1
clear
if [ "$u" = "C" ] || [ "$u" = "c" ]; then
mv /data/data/com.termux/files/usr/glibc /data/data/com.termux/files/usr/glibc3
bash x2
else
echo "Cập nhật thành công."
sleep 1
clear
echo 'Để mở mobox, nhập mobox hoặc nekobox.'
sleep 3
fi
fi
