#!/bin/bash

defitem=1

while true; do
load_configs
dialog_menu_item $defitem "Cài đặt Dynarec" "" \
	"1" "DYNAREC_ALIGNED_ATOMICS\Z2=\Z3$BOX64_DYNAREC_ALIGNED_ATOMICS" \
	"2" "DYNAREC_BIGBLOCK\Z2=\Z3$BOX64_DYNAREC_BIGBLOCK" \
	"3" "DYNAREC_FASTNAN\Z2=\Z3$BOX64_DYNAREC_FASTNAN" \
	"4" "DYNAREC_SAFEFLAGS\Z2=\Z3$BOX64_DYNAREC_SAFEFLAGS" \
	"5" "DYNAREC_STRONGMEM\Z2=\Z3$BOX64_DYNAREC_STRONGMEM" \
	"6" "DYNAREC_WAIT\Z2=\Z3$BOX64_DYNAREC_WAIT" \
	"7" "DYNAREC_X87DOUBLE\Z2=\Z3$BOX64_DYNAREC_X87DOUBLE" \
	"8" "DYNAREC_CALLRET\Z2=\Z3$BOX64_DYNAREC_CALLRET" \
	"9" "DYNAREC_FASTROUND\Z2=\Z3$BOX64_DYNAREC_FASTROUND" \
	"10" "IGNOREINT3\Z2=\Z3$BOX64_IGNOREINT3" \
	"11" "Khôi phục về mặc định " \
	"12" "Chuyển về bộ cấu hình theo mẫu"
defitem=$?
case $defitem in
1)
	case "$BOX64_DYNAREC_ALIGNED_ATOMICS" in
	"") echo "export BOX64_DYNAREC_ALIGNED_ATOMICS=0">$PREFIX/glibc/opt/conf/dynarec/aligned_atomics.conf ;;
	0) echo "export BOX64_DYNAREC_ALIGNED_ATOMICS=1">$PREFIX/glibc/opt/conf/dynarec/aligned_atomics.conf ;;
	1) echo "unset BOX64_DYNAREC_ALIGNED_ATOMICS">$PREFIX/glibc/opt/conf/dynarec/aligned_atomics.conf ;;
	esac
;;

2)
	case "$BOX64_DYNAREC_BIGBLOCK" in
	"") echo "export BOX64_DYNAREC_BIGBLOCK=0">$PREFIX/glibc/opt/conf/dynarec/bigblock.conf ;;
	0) echo "export BOX64_DYNAREC_BIGBLOCK=1">$PREFIX/glibc/opt/conf/dynarec/bigblock.conf ;;
	1) echo "export BOX64_DYNAREC_BIGBLOCK=2">$PREFIX/glibc/opt/conf/dynarec/bigblock.conf ;;
	2) echo "export BOX64_DYNAREC_BIGBLOCK=">$PREFIX/glibc/opt/conf/dynarec/bigblock.conf ;;
	esac
;;
3)
	case "$BOX64_DYNAREC_FASTNAN" in
	"") echo "export BOX64_DYNAREC_FASTNAN=0">$PREFIX/glibc/opt/conf/dynarec/fastnan.conf ;;
	0) echo "export BOX64_DYNAREC_FASTNAN=1">$PREFIX/glibc/opt/conf/dynarec/fastnan.conf ;;
	1) echo "unset BOX64_DYNAREC_FASTNAN">$PREFIX/glibc/opt/conf/dynarec/fastnan.conf ;;
	esac
;;
4)
	case "$BOX64_DYNAREC_SAFEFLAGS" in
	"") echo "export BOX64_DYNAREC_SAFEFLAGS=0">$PREFIX/glibc/opt/conf/dynarec/safeflags.conf ;;
	0) echo "export BOX64_DYNAREC_SAFEFLAGS=1">$PREFIX/glibc/opt/conf/dynarec/safeflags.conf ;;
	1) echo "export BOX64_DYNAREC_SAFEFLAGS=2">$PREFIX/glibc/opt/conf/dynarec/safeflags.conf ;;
	2) echo "unset BOX64_DYNAREC_SAFEFLAGS">$PREFIX/glibc/opt/conf/dynarec/safeflags.conf ;;
	esac
;;
5)
	case "$BOX64_DYNAREC_STRONGMEM" in
	"") echo "export BOX64_DYNAREC_STRONGMEM=0">$PREFIX/glibc/opt/conf/dynarec/strongmem.conf ;;
	0) echo "export BOX64_DYNAREC_STRONGMEM=1">$PREFIX/glibc/opt/conf/dynarec/strongmem.conf ;;
	1) echo "export BOX64_DYNAREC_STRONGMEM=2">$PREFIX/glibc/opt/conf/dynarec/strongmem.conf ;;
	2) echo "export BOX64_DYNAREC_STRONGMEM=3">$PREFIX/glibc/opt/conf/dynarec/strongmem.conf ;;
	3) echo "unset BOX64_DYNAREC_STRONGMEM">$PREFIX/glibc/opt/conf/dynarec/strongmem.conf ;;
	esac
;;
6)
	case "$BOX64_DYNAREC_WAIT" in
	"") echo "export BOX64_DYNAREC_WAIT=0">$PREFIX/glibc/opt/conf/dynarec/wait.conf ;;
	0) echo "export BOX64_DYNAREC_WAIT=1">$PREFIX/glibc/opt/conf/dynarec/wait.conf ;;
	1) echo "unset BOX64_DYNAREC_WAIT">$PREFIX/glibc/opt/conf/dynarec/wait.conf ;;
	esac
;;
7)
	case "$BOX64_DYNAREC_X87DOUBLE" in
	"") echo "export BOX64_DYNAREC_X87DOUBLE=0">$PREFIX/glibc/opt/conf/dynarec/x87double.conf ;;
	0) echo "export BOX64_DYNAREC_X87DOUBLE=1">$PREFIX/glibc/opt/conf/dynarec/x87double.conf ;;
	1) echo "unset BOX64_DYNAREC_X87DOUBLE">$PREFIX/glibc/opt/conf/dynarec/x87double.conf ;;
	esac
;;
8)
	case "$BOX64_DYNAREC_CALLRET" in
	"") echo "export BOX64_DYNAREC_CALLRET=0">$PREFIX/glibc/opt/conf/dynarec/callret.conf ;;
	0) echo "export BOX64_DYNAREC_CALLRET=1">$PREFIX/glibc/opt/conf/dynarec/callret.conf ;;
	1) echo "unset BOX64_DYNAREC_CALLRET">$PREFIX/glibc/opt/conf/dynarec/callret.conf ;;
	esac
;;
9)
	case "$BOX64_DYNAREC_FASTROUND" in
	"") echo "export BOX64_DYNAREC_FASTROUND=0">$PREFIX/glibc/opt/conf/dynarec/fastround.conf ;;
	0) echo "export BOX64_DYNAREC_FASTROUND=1">$PREFIX/glibc/opt/conf/dynarec/fastround.conf ;;
	1) echo "unset BOX64_DYNAREC_FASTROUND">$PREFIX/glibc/opt/conf/dynarec/fastround.conf ;;
	esac
;;
10)
	case "$BOX64_IGNOREINT3" in
	"") echo "export BOX64_IGNOREINT3=0">$PREFIX/glibc/opt/conf/dynarec/ignoreint3.conf ;;
	0) echo "export BOX64_IGNOREINT3=1">$PREFIX/glibc/opt/conf/dynarec/ignoreint3.conf ;;
	1) echo "unset BOX64_IGNOREINT3">$PREFIX/glibc/opt/conf/dynarec/ignoreint3.conf ;;
	esac
;;
11)
	echo "unset BOX64_DYNAREC_ALIGNED_ATOMICS">$PREFIX/glibc/opt/conf/dynarec/aligned_atomics.conf
	echo "export BOX64_DYNAREC_BIGBLOCK=2">$PREFIX/glibc/opt/conf/dynarec/bigblock.conf
	echo "export BOX64_DYNAREC_FASTNAN=0">$PREFIX/glibc/opt/conf/dynarec/fastnan.conf
	echo "unset BOX64_DYNAREC_FASTROUND">$PREFIX/glibc/opt/conf/dynarec/fastround.conf
	echo "export BOX64_DYNAREC_SAFEFLAGS=2">$PREFIX/glibc/opt/conf/dynarec/safeflags.conf
	echo "export BOX64_DYNAREC_STRONGMEM=1">$PREFIX/glibc/opt/conf/dynarec/strongmem.conf
	echo "unset BOX64_DYNAREC_WAIT">$PREFIX/glibc/opt/conf/dynarec/wait.conf
	echo "unset BOX64_DYNAREC_X87DOUBLE">$PREFIX/glibc/opt/conf/dynarec/x87double.conf
	echo "export BOX64_DYNAREC_CALLRET=0">$PREFIX/glibc/opt/conf/dynarec/callret.conf
	echo "unset BOX64_IGNOREINT3">$PREFIX/glibc/opt/conf/dynarec/callret.conf
;;
12)
	echo "export DYNAREC_SETTINGS_SCRIPT=2
export DYNAREC_CURRENT_PRESET=none">$PREFIX/glibc/opt/conf/dynarec_preset.conf
	break
;;
255)
	break
;;
esac
done
