#!/bin/bash

defitem=1

while true; do
load_configs
dialog_menu_item $defitem "Cài đặt môi trường wine" "" \
	"1" "Gỡ cài đặt môi trường" \
	"2" "Đổi chế độ wine sync"
defitem=$?
case $defitem in
1)
	dialog_yesno "Bạn chắc chứ?"
	if [ "$?" = "0" ]; then
		rm -rf $WINEPREFIX
	fi
;;
2)
# 	if [[ ! "$WINE_PATH" = *"wine-9.0-staging-wow64"* ]] || [ ! -e "$WINE_PATH" ]; then
# 		echo "WINEESYNC không mở được do phiên bản wine hiện tại quá cũ."
# 		echo "Bạn muốn cài và tự động mở wine-9.0-staging-wow64  (C/k)"
# 		read i
# 		if [ "$i" = "C" ] || [ "$i" = "c" ]; then
# 			load_package-manager
# 			if [ "$?" = "1" ]; then
# 				continue
# 			fi
# 			sync-package wine-9.0-staging-wow64
# 			echo "export WINE_PATH=\$PREFIX/glibc/wine-9.0-staging-wow64
# export WINEPREFIX=\$PREFIX/glibc/wine-9.0-staging-wow64/.wine">$PREFIX/glibc/opt/conf/wine_path.conf
# 		fi
# 		continue
# 	fi
	while true; do
	load_configs
	dialog_menu "Cài đặt WINEESYNC" "\ZbCài đặt hiện tại:\Zn
	\Z3WINEESYNC\Z2=\Zn$WINEESYNC
	\Z3WINEESYNC không root\Z2=\Zn$WINEESYNC_TERMUX" \
	"1" "Tắt esync" \
	"2" "Mở esync không cần root" \
	"3" "Mở esync với root"
	case $? in
	1) echo "export WINEESYNC=0
export WINEESYNC_TERMUX=0">$PREFIX/glibc/opt/conf/wineesync.conf ;;
	2) echo "export WINEESYNC=1
export WINEESYNC_TERMUX=1">$PREFIX/glibc/opt/conf/wineesync.conf ;;
	3) echo "export WINEESYNC=1
export WINEESYNC_TERMUX=0">$PREFIX/glibc/opt/conf/wineesync.conf ;;
	255) break ;;
	esac
	done
;;
255)
	break
;;
esac
done
