#!/bin/bash

defitem=1

while true; do
load_configs
dialog_menu_item $defitem "Cài đặt về root" "" \
	"1" "Tắt ứng dụng chạy ngầm" \
	"2" "Bộ điều chỉnh OOM (ngăn chặn Termux tự động tắt)" \
	"3" "Tăng số lượng bản đồ vm tối đa (Có thể áp dụng được trên source 2)" \
	"4" "Tắt phantom process killer"
defitem=$?
case $defitem in
1)
	chmod 777 $PREFIX/glibc/opt/scripts/close-apps
	sudo bash $PREFIX/glibc/opt/scripts/close-apps
	sleep 3
;;
2)
	chmod 777 $PREFIX/glibc/opt/scripts/termux-adj
	sudo bash $PREFIX/glibc/opt/scripts/termux-adj &
	echo "Bộ điều chỉnh OOM đang chạy.Đừng dùng cái này nhiều hơn 1 lần, thật đấy! Để dừng nó - buộc dừng Termux"
	sleep 4
;;
3)
	su -c "echo 2147483642 > /proc/sys/vm/max_map_count"
;;
4)
	su -c "/system/bin/device_config put activity_manager max_phantom_processes 2147483647"
;;
255)
	break
;;
esac
done
