#!/bin/bash

defitem_settings=1

while true; do
dialog_menu_item $defitem_settings "Cài đặt" "" \
"1" "Cài đặt Dynarec" \
"2" "Cài đặt môi trường wine (+ESYNC)" \
"3" "Cài đặt DXVK" \
"4" "Cài đặt hệ thống" \
"5" "Cài đặt về gỡ lỗi" \
"6" "Cài đặt về Root" \
"7" "Cài đặt về VirGL" \
"8" "Sao lưu và khôi phục" \
"9" "Cài đặt tương thích thiết bị" \
"10" "Cài đặt Wine desktop"

defitem_settings=$?
case $defitem_settings in
1)
        . $PREFIX/glibc/opt/conf/dynarec_preset.conf
        if [ "$DYNAREC_SETTINGS_SCRIPT" = "1" ]; then
                . $PREFIX/glibc/opt/scripts/dynarec-settings
        else
                . $PREFIX/glibc/opt/scripts/dynarec2-settings
        fi
;;
2)
        . $PREFIX/glibc/opt/scripts/prefix-settings
;;
3)
        . $PREFIX/glibc/opt/scripts/dxvk-settings
;;
4)
        . $PREFIX/glibc/opt/scripts/system-settings
;;
5)
        defitem=1
        while true; do
        load_configs
        dialog_menu_item $defitem "Cài đặt gỡ lỗi" "\ZbCài đặt hiện tại:\Zn
        \Z3MESA_NO_ERROR\Z2=\Zn$MESA_NO_ERROR
        \Z3WINEDEBUG\Z2=\Zn$WINEDEBUG
        \Z3BOX64_LOG\Z2=\Zn$BOX64_LOG
        \Z3BOX64_SHOWSEGV\Z2=\Zn$BOX64_SHOWSEGV
        \Z3BOX64_DYNAREC_MISSING\Z2=\Zn$BOX64_DYNAREC_MISSING
        \Z3BOX64_TRACE_FILE\Z2=\Zn$BOX64_TRACE_FILE\Zn" \
"1" "Tắt gỡ lỗi" \
"2" "Mở gỡ lỗi ($LOG_PATH)" \
"3" "Mở gỡ lỗi kèm chi tiết ($LOG_PATH)"
        defitem=$?
        case $defitem in
        1) echo "export DEBUG_MODE=0">$PREFIX/glibc/opt/conf/debug.conf ;;
        2) echo "export DEBUG_MODE=1">$PREFIX/glibc/opt/conf/debug.conf ;;
        3) echo "export DEBUG_MODE=2">$PREFIX/glibc/opt/conf/debug.conf ;;
        255) break ;;
        esac
        done
;;
6)
        . $PREFIX/glibc/opt/scripts/root-settings
;;
7)
        . $PREFIX/glibc/opt/scripts/virgl-settings
;;
8)
        . $PREFIX/glibc/opt/scripts/restore-menu
;;
9)
        . $PREFIX/glibc/opt/scripts/compatibility-settings
;;
10)
manage_wine_desktop() {
    status_file=".wine_desktop_status.txt"

    if [ ! -f "$status_file" ]; then
        echo "on" > "$status_file"
    fi

    current_status=$(cat "$status_file")

    if [ "$current_status" = "on" ]; then
        echo "Wine Desktop đang bật."
    else
        echo "Wine Desktop đang tắt."
    fi

    echo "Chọn lựa chọn về Wine Desktop
    [1] Mở/tắt
    "
    read s

    if [ "$s" = "1" ]; then
        if [ "$current_status" = "on" ]; then
            mv $PREFIX/glibc/opt/scripts/start-tfm $PREFIX/glibc/opt/scripts/start-tfm2
            mv $PREFIX/glibc/opt/scripts/start-tfm3 $PREFIX/glibc/opt/scripts/start-tfm
mv $PREFIX/glibc/opt/scripts/start-tfm2 $PREFIX/glibc/opt/scripts/start-tfm3
            echo "Wine Desktop đã bị tắt."
            echo "off" > "$status_file" 
        else
	mv $PREFIX/glibc/opt/scripts/start-tfm $PREFIX/glibc/opt/scripts/start-tfm2
            mv $PREFIX/glibc/opt/scripts/start-tfm3 $PREFIX/glibc/opt/scripts/start-tfm
mv $PREFIX/glibc/opt/scripts/start-tfm2 $PREFIX/glibc/opt/scripts/start-tfm3
            echo "Wine Desktop đã được bật."
            echo "on" > "$status_file"  
        fi
    fi
}

dialog_menu "Cài đặt Wine desktop" "" \
    "1" "Bật/tắt Wine Desktop" \
    "2" "Cài DE/WM trong Termux"

ret2=$?
if [ $ret2 -eq 255 ]; then
    continue
fi

case $ret2 in
    1) manage_wine_desktop ;; 
    255) break ;;
esac
;;
255)
    break
;;
esac
done
