#!/bin/bash

defitem=1

while true; do
load_configs
dialog_menu_item $defitem "Cài đặt hệ thống" "\ZbCài đặt hiện tại:\Zn
	\Z3LÕI CPU CHÍNH\Z2=\Zn$PRIMARY_CORES
	\Z3LÕI CPU PHỤ\Z2=\Zn$SECONDARY_CORES
	\Z3NGÔN NGỮ\Z2=\Zn$(cat $PREFIX/glibc/opt/locale.conf)
	\Z3HUD DXVK\Z2=\Zn$DXVK_HUD
	\Z3GALLIUM HUD\Z2=\Zn$GALLIUM_HUD
	\Z3GỠ LỖI TU\Z2=\Zn$TU_DEBUG
	\Z3CHẾ ĐỘ HIỆN TẠI CỦAMESA VK WSI\Z2=\Zn$MESA_VK_WSI_PRESENT_MODE
	\Z3ĐỘ PHÂN GIẢI HIỆN TẠI\Z2=\Zn$(cat $PREFIX/glibc/opt/last-resolution.conf)\Zn" \
	"1" "Thay đổi độ phân giải" \
	"2" "Thay đổi số lõi CPU chính" \
	"3" "Đổi ngôn ngữ" \
	"4" "Thay đổi mẫu HUD" \
	"5" "Chọn TU_DEBUG" \
	"6" "Chỉnh về mặc định"
defitem=$?
case $defitem in
1)
	i=$(dialog_inputbox "Nhập độ phân giải mới (v.d 1280x720)")
	if [ $? = 1 ] || [ "$i" = "" ]; then continue; fi
	echo "$i">$PREFIX/glibc/opt/last-resolution.conf
;;
2)
	dialog_menu "" "Chọn số lõi CPU chính mà bạn muốn dùng. (mặc định - 7)" \
	"2" ""\
	"3" ""\
	"4" ""\
	"5" ""\
	"6" ""\
	"7" ""\
	"8" ""
	case $? in
	2) echo "export PRIMARY_CORES=6-7
export SECONDARY_CORES=0-5">$PREFIX/glibc/opt/conf/cores.conf ;;
	3) echo "export PRIMARY_CORES=5-7
export SECONDARY_CORES=0-4">$PREFIX/glibc/opt/conf/cores.conf ;;
	4) echo "export PRIMARY_CORES=4-7
export SECONDARY_CORES=0-3">$PREFIX/glibc/opt/conf/cores.conf ;;
	5) echo "export PRIMARY_CORES=3-7
export SECONDARY_CORES=0-2">$PREFIX/glibc/opt/conf/cores.conf ;;
	6) echo "export PRIMARY_CORES=2-7
export SECONDARY_CORES=0-1">$PREFIX/glibc/opt/conf/cores.conf ;;
	7) echo "export PRIMARY_CORES=1-7
export SECONDARY_CORES=0-1">$PREFIX/glibc/opt/conf/cores.conf ;;
	8) echo "export PRIMARY_CORES=0-7
export SECONDARY_CORES=0-1">$PREFIX/glibc/opt/conf/cores.conf ;;
	
	esac
;;
3)
	i=$(dialog_inputbox "Nhập ngôn ngữ mới. (v.d vi_VN)")
	if [ $? = 1 ] || [ "$i" = "" ]; then continue; fi
	echo "$i.utf8">$PREFIX/glibc/opt/locale.conf
;;
4)
	dialog_menu "" "" \
"1" "Tắt gallium and dxvk hud" \
"2" "Bật bộ đếm fps" \
"3" "Bật bộ đếm kèm chi tiết dxvk hud, gallium fps"
	case $? in
	1)
		echo "unset GALLIUM_HUD
export GALLIUM_HUD_PERIOD=1
unset DXVK_HUD">$PREFIX/glibc/opt/conf/hud.conf
	;;
	2)
		echo "export GALLIUM_HUD=simple,fps
export GALLIUM_HUD_PERIOD=1
export DXVK_HUD=version,fps,scale=0.7">$PREFIX/glibc/opt/conf/hud.conf
	;;
	3)
		echo "export GALLIUM_HUD=simple,fps
export GALLIUM_HUD_PERIOD=1
export DXVK_HUD=version,fps,api,scale=0.7,devinfo,gpuload,frametimes">$PREFIX/glibc/opt/conf/hud.conf
	;;
	esac
;;
5)
	dialog_menu "" "" \
"1" "TU_DEBUG=noconform" \
"2" "TU_DEBUG=noconform,syncdraw (slow)" \
"3" "TU_DEBUG=noconform,syncdraw,flushall (slower)"
	case $? in
	1)
		echo "export TU_DEBUG=noconform">$PREFIX/glibc/opt/conf/tu_debug.conf
	;;
	2)
		echo "export TU_DEBUG=noconform,syncdraw">$PREFIX/glibc/opt/conf/tu_debug.conf
	;;
	3)
		echo "export TU_DEBUG=noconform,syncdraw,flushall">$PREFIX/glibc/opt/conf/tu_debug.conf
	;;
	esac
;;
6)
	cp $PREFIX/glibc/opt/default-conf/conf/{cores.conf,hud.conf,tu_debug.conf,wsi_present.conf} $PREFIX/glibc/opt/conf
	cp $PREFIX/glibc/opt/default-conf/{last-resolution.conf,locale.conf} $PREFIX/glibc/opt
;;
255)
	break
;;
esac
done
